AllCops:
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - spec/dummy/db/migrate/**/*
    - spec/dummy/db/schema.rb
    - Gemfile
    - Guardfile
    - Rakefile





Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/LambdaCall:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
  # EnforcedStyle: semantic
  # FunctionalMethods:
  #   - let
  #   - let!
  #   - subject
  #   - routes

Style/NestedParenthesizedCalls:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  # EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantReturn:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/MutableConstant:
  Enabled: false





Layout/IndentArray:
  EnforcedStyle: consistent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

# Temp fix
# expect("...").to \
# eq("...")
Layout/FirstParameterIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# create(:foo, bar: 1+1)
Layout/SpaceAroundOperators:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented





Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - t.index
    - table.
    - add_index
    - secret
    - config.pepper

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
